// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Repositories.EfCore;

#nullable disable

namespace _5_LayeredArchitecture.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20230501144201_mig_3")]
    partial class mig_3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Blok")
                        .HasColumnType("text");

                    b.Property<string>("Nitelik")
                        .HasColumnType("text");

                    b.Property<double?>("X")
                        .HasColumnType("double precision");

                    b.Property<double?>("Y")
                        .HasColumnType("double precision");

                    b.Property<int?>("fKey")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Buildings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Blok = "b1",
                            Nitelik = "n1",
                            X = 39.100000000000001,
                            Y = 33.100000000000001,
                            fKey = 1
                        },
                        new
                        {
                            Id = 2,
                            Blok = "b2",
                            Nitelik = "n2",
                            X = 39.0,
                            Y = 33.0,
                            fKey = 2
                        });
                });

            modelBuilder.Entity("Entities.Models.Parcel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Ada")
                        .HasColumnType("integer");

                    b.Property<string>("Pafta")
                        .HasColumnType("text");

                    b.Property<int?>("ParcelNo")
                        .HasColumnType("integer");

                    b.Property<int?>("X")
                        .HasColumnType("integer");

                    b.Property<int?>("Y")
                        .HasColumnType("integer");

                    b.Property<string>("il")
                        .HasColumnType("text");

                    b.Property<string>("ilce")
                        .HasColumnType("text");

                    b.Property<string>("mahalle")
                        .HasColumnType("text");

                    b.Property<string>("nitelik")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Parcels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ada = 1,
                            Pafta = "p1",
                            ParcelNo = 1,
                            il = "il1",
                            ilce = "ilce1",
                            mahalle = "m1",
                            nitelik = "n1"
                        },
                        new
                        {
                            Id = 2,
                            Ada = 2,
                            Pafta = "p2",
                            ParcelNo = 2,
                            il = "il2",
                            ilce = "ilce2",
                            mahalle = "m2",
                            nitelik = "n2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
