// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Repositories.EfCore;

#nullable disable

namespace _5_LayeredArchitecture.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Blok")
                        .HasColumnType("text");

                    b.Property<string>("Nitelik")
                        .HasColumnType("text");

                    b.Property<int?>("fKey")
                        .HasColumnType("integer");

                    b.Property<MultiPolygon>("geom")
                        .HasColumnType("geometry");

                    b.HasKey("Id");

                    b.ToTable("Buildings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Blok = "b1",
                            Nitelik = "n1",
                            fKey = 1
                        },
                        new
                        {
                            Id = 2,
                            Blok = "b2",
                            Nitelik = "n2",
                            fKey = 2
                        });
                });

            modelBuilder.Entity("Entities.Models.Parcel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Ada")
                        .HasColumnType("integer");

                    b.Property<string>("Pafta")
                        .HasColumnType("text");

                    b.Property<int?>("ParselNo")
                        .HasColumnType("integer");

                    b.Property<MultiPolygon>("geom")
                        .HasColumnType("geometry");

                    b.Property<string>("il")
                        .HasColumnType("text");

                    b.Property<string>("ilce")
                        .HasColumnType("text");

                    b.Property<string>("mahalle")
                        .HasColumnType("text");

                    b.Property<string>("nitelik")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Parcels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ada = 1,
                            Pafta = "p1",
                            ParselNo = 1,
                            il = "il1",
                            ilce = "ilce1",
                            mahalle = "m1",
                            nitelik = "n1"
                        },
                        new
                        {
                            Id = 2,
                            Ada = 2,
                            Pafta = "p2",
                            ParselNo = 2,
                            il = "il2",
                            ilce = "ilce2",
                            mahalle = "m2",
                            nitelik = "n2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
